name: tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          #comment

      - name: testsgit br
        run: python -m pytest --cov=./tests --cov-report xml

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        #uses: coverallsapp/github-action@master
        #uses: coverallsapp/github-action@1.1.3

        with:
          parallel: true
          flag-name: testsgit br
          #flag-name: testsgit br
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.xml
