name: tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Python 3
        uses: actions/setup-python@v3
        with:
            python-version:: '3.8'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: tests
        run: pytest

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
